language: python

python:
  - 3.8

env:
  global:
    - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
    - DATABASE_HOST=$DATABASE_HOST
    - DATABASE_NAME=$DATABASE_NAME
    - DATABASE_USER=$DATABASE_USER
    - DATABASE_PASS=$DATABASE_PASS
    - DATABASE_PORT=$DATABASE_PORT

install:
  - pip install -r requirements.txt

# before_script:
#   - python manage.py migrate
#   - python manage.py collectstatic --noinput

script:
  - flake8 --exclude=migrations --max-line-length=88
  - black --check --exclude=migrations .
  - python manage.py test

# deploy:
#   provider: elasticbeanstalk
#   access_key_id:
#     secure: $AWS_ACCESS_KEY_ID
#   secret_access_key:
#     secure: $AWS_SECRET_ACCESS_KEY
#   region: "us-east-1"
#   app: "django-polls"
#   env: "django-polls-dev"
#   bucket_name: "elasticbeanstalk-us-east-1-919736960713"
